### ISSUE TITLE
Question about configure

### ISSUE THREAD

**Issue by farzadha2** [bartmichu/urbackup-extras#1]
HI I  was looking at the repo but didnt find the guide to install it on zabbix and configure?
I assume this monitor   urbackup on zabbix?

**Comment by bartmichu** [comment]
Hi @farzadha2 
This is a very basic template to monitor the state of UrBackup server/client service and package. You can find usage instructions in the header of _userparams_ file, just open it via GitHub. Let me know if you need further assistance.

If you are looking for more detailed info from the server, like the number of failed clients, you can use [urbstat tool](https://github.com/bartmichu/urbstat). This is exactly what I'm doing on my servers, unfortunately the Zabbix template file is not public at the moment.
